apiVersion: v1
kind: Service
metadata:
    name: debrowser-nginx
spec:
    ports:
        -   port: 80
            targetPort: 80
            protocol: TCP
            name: http
    selector:
        app: debrowser-nginx

---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: debrowser-nginx
spec:
    replicas: 1
    selector:
        matchLabels:
            app: debrowser-nginx
    template:
        metadata:
            labels:
                app: debrowser-nginx
        spec:
            containers:
                -   name: debrowser-nginx
                    image: docker.pkg.github.com/extraton/debrowser/debrowser-nginx:0.1.2
                    ports: [{containerPort: 80}]
            imagePullSecrets:
                -   name: github-registry
